# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170824_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, verbose_name='\u6536\u85cf\u4eba\u6570'),
        ),
    ]
