# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='desc',
            field=models.CharField(default='', max_length=100, verbose_name='\u6559\u5e08\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u6559\u5e08\u540d\u5b57'),
        ),
    ]
