# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-24 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='course',
            new_name='lesson',
        ),
    ]
